version: "3.9"

services:
  db:
    container_name: tonnftscan.db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    ports:
      - "5435:5432"
  app:
    container_name: tonnftscan.app
    environment:
      DJANGO_SETTINGS_MODULE: tonnftscan.settings
    build:
      context: .
      dockerfile: Dockerfile
    image: tonnftscan_image
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && /usr/local/bin/gunicorn tonnftscan.wsgi:application --log-level debug --bind 0.0.0.0:8008 --workers=20 --timeout 90"
    volumes:
      - ./var:/var
      - ./tonnftscan:/tonnftscan
      - ./templates:/templates
      - ./.env:/.env
    links:
      - db
    depends_on:
      - db
    ports:
      - "8008:8008"
    deploy:
      restart_policy:
        condition: on-failure
    restart: unless-stopped