# Generated by Django 4.0.5 on 2023-12-27 14:50

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("address", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_scam", models.BooleanField(default=False)),
                ("is_wallet", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("address", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=2000)),
                ("description", models.CharField(max_length=10000)),
                (
                    "social_links",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.CharField(max_length=1000), size=None
                    ),
                ),
                ("marketplace", models.CharField(max_length=1000)),
                ("image", models.CharField(max_length=1000)),
                ("cover_image", models.CharField(max_length=1000)),
                ("external_url", models.CharField(max_length=1000)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tonnftscan.useraddress")),
            ],
        ),
    ]
