# Generated by Django 4.0.5 on 2023-12-27 14:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="cover_image",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="collection",
            name="external_url",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="collection",
            name="social_links",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=10000), size=None
            ),
        ),
    ]
