# Generated by Django 4.0.5 on 2023-12-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0002_alter_collection_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tonnftscan.useraddress"
            ),
        ),
    ]
