# Generated by Django 4.0.5 on 2023-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0004_nft"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nft",
            name="approved_by",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="nft",
            name="sale",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="nft",
            name="transactions_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nft",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
