# Generated by Django 4.0.5 on 2023-12-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0006_alter_nft_sale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAddress",
            new_name="Address",
        ),
        migrations.AddField(
            model_name="nft",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
