# Generated by Django 4.0.5 on 2023-12-28 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0007_rename_useraddress_address_nft_last_fetched_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_hex", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="TransactionAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=1000)),
                ("status", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nft",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tonnftscan.nft"
                    ),
                ),
                (
                    "recipient_address",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tonnftscan.address"
                    ),
                ),
                (
                    "sender_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="tonnftscan.address",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tonnftscan.transaction"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="account_address",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tonnftscan.address"
            ),
        ),
    ]
