# Generated by Django 4.0.5 on 2023-12-28 22:54

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0008_transaction_address_name_transactionaction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nft",
            name="transactions_fetched_at",
        ),
        migrations.AddField(
            model_name="address",
            name="balance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="icon",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="interfaces",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=1000), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="last_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="status",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
