# Generated by Django 4.0.5 on 2023-12-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0010_alter_address_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.CharField(db_index=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="nft",
            name="description",
            field=models.CharField(db_index=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="nft",
            name="name",
            field=models.CharField(db_index=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="nft",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfts",
                to="tonnftscan.address",
            ),
        ),
    ]
