# Generated by Django 4.2.8 on 2024-01-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0012_alter_collection_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfts",
                to="tonnftscan.collection",
            ),
        ),
    ]
