# Generated by Django 4.2.8 on 2024-01-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0013_alter_nft_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="nfts_count",
            field=models.IntegerField(default=0),
        ),
    ]
