# Generated by Django 4.2.8 on 2024-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0015_collection_pushed_to_google_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                blank=True, choices=[("wallet", "Wallet"), ("nft_sale", "NFT Sale")], max_length=256, null=True
            ),
        ),
    ]
