# Generated by Django 4.2.8 on 2024-01-12 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0017_remove_address_is_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTTransactionAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transaction_hex", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=1000)),
                ("type", models.CharField(max_length=1000)),
                ("timestamp", models.DateTimeField()),
                (
                    "nft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="tonnftscan.nft"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to="tonnftscan.address",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transactions",
                        to="tonnftscan.address",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="transactionaction",
            name="nft",
        ),
        migrations.RemoveField(
            model_name="transactionaction",
            name="recipient_address",
        ),
        migrations.RemoveField(
            model_name="transactionaction",
            name="sender_address",
        ),
        migrations.RemoveField(
            model_name="transactionaction",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.DeleteModel(
            name="TransactionAction",
        ),
    ]
