# Generated by Django 4.2.8 on 2024-01-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0018_nfttransactionaction_remove_transactionaction_nft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="num_of_transactions",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
