# Generated by Django 4.2.8 on 2024-01-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0019_nft_num_of_transactions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionSearch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "google_impressions_total",
                    models.IntegerField(default=0, help_text="Number of impressions in Google"),
                ),
                (
                    "google_impressions_last_30_days",
                    models.IntegerField(default=0, help_text="Number of impressions in Google for the last 30 days"),
                ),
                ("google_clicks_total", models.IntegerField(default=0, help_text="Number of clicks in Google")),
                (
                    "google_clicks_last_30_days",
                    models.IntegerField(default=0, help_text="Number of clicks in Google for the last 30 days"),
                ),
                (
                    "google_clicks_last_7_days",
                    models.IntegerField(default=0, help_text="Number of clicks in Google for the last 7 days"),
                ),
                ("google_ctr_total", models.FloatField(default=0, help_text="CTR in Google")),
                (
                    "google_ctr_last_30_days",
                    models.FloatField(default=0, help_text="CTR in Google for the last 30 days"),
                ),
                ("google_position_total", models.FloatField(default=0, help_text="Position in Google")),
                (
                    "google_position_last_30_days",
                    models.FloatField(default=0, help_text="Position in Google for the last 30 days"),
                ),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_data",
                        to="tonnftscan.collection",
                    ),
                ),
            ],
        ),
    ]
