# Generated by Django 4.2.8 on 2024-01-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0022_dailyindicator_alter_collectionsearch_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="nfts_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
