# Generated by Django 4.2.8 on 2024-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tonnftscan", "0023_address_nfts_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
