# Generated by Django 4.2.8 on 2024-02-11 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0024_alter_nft_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionsearch",
            name="collection",
        ),
        migrations.DeleteModel(
            name="DailyIndicator",
        ),
        migrations.DeleteModel(
            name="CollectionSearch",
        ),
    ]
