# Generated by Django 4.2.8 on 2024-02-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionindicators",
            name="spread_historical",
            field=models.JSONField(
                blank=True, default=list, help_text="Number of wallets who owned NFTs over time", null=True
            ),
        ),
        migrations.AddField(
            model_name="collectionindicators",
            name="spread_ratio_current",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Spread ratio: number of wallets with NFTs from collection / total number of NFTs",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="collectionindicators",
            name="spam_ratio",
            field=models.FloatField(
                blank=True, default=0, help_text="Spam ratio: burned NFTs / total NFTs in the collection", null=True
            ),
        ),
    ]
