# Generated by Django 4.2.8 on 2024-02-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tonnftscan", "0025_remove_collectionsearch_collection_and_more"),
        ("indicators", "0002_collectionindicators_spread_historical_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionindicators",
            name="spread_historical",
        ),
        migrations.AlterField(
            model_name="collectionindicators",
            name="collection",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_indicators",
                to="tonnftscan.collection",
            ),
        ),
        migrations.AlterField(
            model_name="collectionindicators",
            name="spam_ratio",
            field=models.FloatField(
                blank=True, default=None, help_text="Spam ratio: burned NFTs / total NFTs in the collection", null=True
            ),
        ),
        migrations.AlterField(
            model_name="collectionindicators",
            name="spread_ratio_current",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="Spread ratio: number of wallets with NFTs from collection / total number of NFTs",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CollectionIndicatorsPercentiles",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "spam_ratio",
                    models.FloatField(blank=True, default=None, help_text="Spam ratio percentile", null=True),
                ),
                (
                    "spread_ratio_current",
                    models.FloatField(blank=True, default=None, help_text="Spread ratio percentile", null=True),
                ),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_indicators_percentiles",
                        to="tonnftscan.collection",
                    ),
                ),
            ],
        ),
    ]
