# Generated by Django 4.2.8 on 2024-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0003_remove_collectionindicators_spread_historical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionindicators",
            name="spread_historical",
            field=models.FloatField(
                blank=True, default=None, help_text="Number of wallets who owned NFTs over time", null=True
            ),
        ),
    ]
